//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int OrderID { get; set; }
        public string PayType { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> CVV { get; set; }
        public string UpiID { get; set; }
        public decimal Amount { get; set; }
        public string PayStatus { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
